"""empty message

Revision ID: 2aded2b8e1f0
Revises: 
Create Date: 2018-04-11 16:06:48.552546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aded2b8e1f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=25), nullable=True),
    sa.Column('model_id', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('user_role', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.String(length=12), nullable=True),
    sa.Column('regNum', sa.Integer(), nullable=True),
    sa.Column('droneNum', sa.Integer(), nullable=True),
    sa.Column('pilot', sa.String(length=32), nullable=True),
    sa.Column('pilotNum', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('weather', sa.String(length=16), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('drones')
    # ### end Alembic commands ###
